---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  - generateName: express-sample-app-pipeline-run-
spec:
  pipelineRef:
    name: nodejs-pipeline
  params:
    - name: source-repo
      value: https://github.com/alexseymour1997/express-sample-app
  workspaces:
    - name: pipeline-shared-data
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
