apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
name: print-readme # error
spec:
  steps:
    - name: print-readme
      image: quay.io/ibmgaragecloud/alpine-curl
      script: |
        cat dir-with-readme/README.md
  workspace: # error
    - name: dir-with-readme
